### ISSUE TITLE
Sequence of Tasks Must be Completed by Same Resource

### ISSUE THREAD

**Issue by bash-j** [timnon/pyschedule#1]
Great work so far on pyschedule!

I have a question on how to do something, or possibly a feature request.

How can I define that a series of tasks must be completed by the same resource?

For example a truck delivering goods can make a round trip from the depot to the customer and back again. While one truck is unloading at the customer, a second truck could be driving to the customer. But I don't want to schedule for the 2nd truck to complete the unloading of the 1st truck.

````
S = pyschedule.Scenario('delivery')

# Two trucks
Truck_A = S.Resource('A')
Truck_B = S.Resource('B')

# Two deliveries
a_deliver, a_unload, a_return = S.Task('a_deliver', 30), S.Task('a_unload', 15), S.Task('a_return', 30)
b_deliver, b_unload, b_return = S.Task('b_deliver', 30), S.Task('b_unload', 15), S.Task('b_return', 30)

# Task sequences
S += a_deliver < a_unload, a_unload < a_return
S += b_deliver < b_unload, b_unload < b_return

# Customer
customer = S.Resource('customer')

# Only one resource (dock) for customer
a_unload += customer
b_unload += customer

# Task can be assigned to either truck
a_deliver += Truck_A | Truck_B
a_unload += Truck_A | Truck_B
a_return += Truck_A | Truck_B
b_deliver += Truck_A | Truck_B
b_unload += Truck_A | Truck_B
b_return += Truck_A | Truck_B

pyschedule.solvers.pulp.solve(S)
```
Which returned this solution:
```

##############################################

SCENARIO: delivery

OBJECTIVE: 

RESOURCES:
A
B
customer

TASKS:
a_deliver at 45 on [A] : [A | B]
a_unload at 75 on [customer, B] : [customer, A | B]
a_return at 90 on [B] : [A | B]
b_deliver at 0 on [A] : [A | B]
b_unload at 30 on [customer, B] : [customer, A | B]
b_return at 45 on [B] : [A | B]

PRECEDENCES:
a_deliver < a_unload
a_unload < a_return
b_deliver < b_unload
b_unload < b_return

##############################################
```

As you can see, because I do not know how to set a constraint with one resource per task group, it scheduled Truck_A to deliver both deliveries, but Truck_B to unload and return.

**Comment by timnon** [comment]
Hi,

Thanks for raising the issue! Very good point, this option can be switched on using the scenario-level parameter is_same_resource_precs_lax (scenario.is_same_resource_precs_lax = True). This works for the solvers pulp.solve_discrete and ortools.solve (check the overview wiki page for current solvers).  Note that both solvers require a horizon-parameter, which is an upper bound on the number of required time periods, try 100 in your case. The solver pulp.solve_discrete is a little sensitive with respect to that number, so it should be below around 300.

However, I was not so happy with switching this option on/off on a scenario-level, there should be a more fine-grained option, any suggestions are welcome.  

One suggestion, maybe if different tasks are added to the same alternative resources, then it is assumed that they all require an arbitrary one, but it should be the same, like:

Truck1 | Truck2 += a_deliver, a_unload, a_return

The goal is to keep the syntax simple and intuitive, but your issue is an important one, there needs to be a no-thrill option.

I will look into implementing this asap, but I am abroad for a few more days, writing this from my mobile phone.

Thanks again for the issue, the idea is to grow pyschedule according to real needs.

Best,
Tim

**Comment by bash-j** [comment]
Thanks Tim,

The ````scenario.is_same_resource_precs_lax = True```` worked.

I noticed the solution had b_deliver before a_deliver, which was okay since I didn't define a constraint. So I added a constraint to the scenario:

````S += a_unload < b_unload````

Now, I'm guessing because of the same resource rule, both deliveries were assigned to the same truck? I noticed there is a similar rule for tight constraints, so I changed the constraint to be a tight one:

````S += a_unload <= b_unload````

This worked and now has the two deliveries on two trucks.

Syntax is an interesting one. As a programmer working in a logistics business with not much experience in mathematics, I like to use functions more than operators. This helps me read out what's happening and make sense of it. Explicit is better than implicit, I would suggest not having assumptions made by the solver, as it would be hard to figure out what is causing the unexpected behaviour. In the case of sequences, maybe something like: 

````
task1 = pyschedule.Sequence([task1_seq1, task1_seq2, task1_seq3],
                             resources=[Bob, Alice],
                             same_resource=True)
````

**Comment by timnon** [comment]
Yes, using too many operator tricks might make things a little blurry. I tried to use them so far whenever it makes sense, but it is probably necessary to divert from this strict rule at some point.

The important thing is where a same-resource-rule gets saved. At the moment there is one global constraints list on the scenario level which makes it easy too add new ones. To encode this additional constraint, just another one should be added that holds the respective tasks plus resources. But then there is some redundancy with respect to the resource requirements list of tasks......... Tricky thing to do this in a clean way:(

Which syntax is used to add such a constraint is then the next problem, will look into this once back.

**Comment by timnon** [comment]
Hi,
i changed the architecture a little which also had a non-backward compatible effect on the syntax. In a nutshell: 

- resource requirements are not saved at the tasks any more but in the global constraints list (S.constraints for a scenario S). This is necessary to allow many-to-many relationships without doing dirty tricks. I have some other things in mind where this should be also the better solution.

- the corresponding constraint is ResourceReq(tasks,resources). Having such a constraint in S.constraint ensures that all tasks pick the same alternative resource from resources. Note that, in a duck-typing style, resources can be any object that iterates over some resources (list,dict,...)

- Hence, for the use case above, we should use ResourceReq(tasks=[a_deliver, a_unload, a_return], resources=[Truck_1,Truck_2])

- Instead of resources=[Truck_1,Truck_2] we can also use resources=Truck_1|Truck_2, which is just a fancy syntax for { Truck_1:1, Truck_2:1 }. Having the size requirement information is not necessary for unit size resources like trucks but helpful for cumulative resources like worker pools where we have e.g. 10 similar workers and sometimes need 2, see CUMUL constraint.

- to keep a declarative language type of syntax, the constraint above can also be generated using Truck_1 | Truck_2 % [a_deliver, a_unload, a_return], the operator % is used from now on as the operator to connect tasks and resources in some way (this is the maximum operator magic that will be used, no more additional operators, but i think it is important to offer the possibility to write basic use cases in a concise way which looks more like a modelling and not so much like a programming language)

- since ResourceReq is a normal constraint, it can be simply be added with method S.add_constraint or via S += which channels an added object to the right place. Hence, we can either write

S.add_constraint(ResourceReq(tasks=[a_deliver, a_unload, a_return], resources=[Truck_1,Truck_2])

or use the shortcut (which does exactly the same thing):

S += Truck_1 | Truck_2 % [a_deliver, a_unload, a_return]

- other possible constraints are S += a_deliver % Truck_1 | Truck_2 (a_deliver used either Truck_1 or Truck_2) or S += a_deliver % [Truck_1,Truck_2] (a_deliver uses Truck_1 and Truck_2, generates two constraints)

I would be happy to get any feedback about possible use cases. Just a note, pick-up-and-delivery-type problems require the solving of TSP-instances, which MIP-solvers are notoriously very bad at. Usually search heuristics are used here which are not supported yet.

If there is a simple example which suffers from a long running time, please post this as an issue (it certainly is)

cheers,
Tim

**Comment by bash-j** [comment]
I like the changes you have made and they make sense, win win!

I have changed my example to use the new functionality and I receive a ````TypeError: 'Resource' object is not iterable````

````
import pyschedule
from pyschedule import ResourceReq
S = pyschedule.Scenario('delivery')
S.is_same_resource_precs_lax = True

# Two trucks
Truck_A = S.Resource('A')
Truck_B = S.Resource('B')

# Customer
Customer = S.Resource('Customer')

# Two deliveries
a_deliver, a_unload, a_return = S.Task('a_deliver', 30), S.Task('a_unload', 15, resources=Customer), S.Task('a_return', 30)
b_deliver, b_unload, b_return = S.Task('b_deliver', 30), S.Task('b_unload', 15, resources=Customer), S.Task('b_return', 30)

# Only one resource (dock) for customer
S += a_unload % Customer
S += b_unload % Customer

# Task can be assigned to either truck
S.add_constraint(ResourceReq(tasks=[a_deliver, a_unload, a_return],
                             resources=[Truck_A, Truck_B]))

S.add_constraint(ResourceReq(tasks=[b_deliver, b_unload, b_return],
                             resources=[Truck_A, Truck_B]))
# Task sequences
S += a_deliver < a_unload, a_unload < a_return
S += b_deliver < b_unload, b_unload < b_return

# a_unload must happen before b_unload
S += a_unload <= b_unload

S.use_makespan_objective()

pyschedule.solvers.pulp.solve_discrete(S, horizon=100)
````

Here is the stacktrace:
````
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-5c240bcfd972> in <module>()
----> 1 pyschedule.solvers.pulp.solve_discrete(S, horizon=100)

C:\Anaconda3\lib\site-packages\pyschedule-0.2.1-py3.4.egg\pyschedule\solvers\pulp.py in solve_discrete(scenario, horizon, kind, time_limit, task_groups, msg, return_copy)
     78         if return_copy :
     79                 scenario = copy.deepcopy(scenario)
---> 80         DiscreteMIP().solve(scenario,horizon,kind=kind,time_limit=time_limit,task_groups=task_groups,msg=msg)
     81         return scenario
     82 

C:\Anaconda3\lib\site-packages\pyschedule-0.2.1-py3.4.egg\pyschedule\solvers\pulp.py in solve(self, scenario, horizon, kind, time_limit, task_groups, msg)
    559                 self.horizon = horizon
    560                 self.task_groups = task_groups
--> 561                 self.build_mip_from_scenario(msg=msg)
    562 
    563                 #if time_limit :

C:\Anaconda3\lib\site-packages\pyschedule-0.2.1-py3.4.egg\pyschedule\solvers\pulp.py in build_mip_from_scenario(self, msg)
    313                                 # fix resources if they are given
    314                                 # TODO: fixed resources not really tested
--> 315                                 resources = [ R for T_ in self.task_groups[T] if T_.resources is not None for R in T_.resources ]
    316                                 for R in resources :
    317                                         if R in S.resources(task=T) :

C:\Anaconda3\lib\site-packages\pyschedule-0.2.1-py3.4.egg\pyschedule\solvers\pulp.py in <listcomp>(.0)
    313                                 # fix resources if they are given
    314                                 # TODO: fixed resources not really tested
--> 315                                 resources = [ R for T_ in self.task_groups[T] if T_.resources is not None for R in T_.resources ]
    316                                 for R in resources :
    317                                         if R in S.resources(task=T) :

TypeError: 'Resource' object is not iterable
````

**Comment by timnon** [comment]
hi, in the creation of a task, the parameter `resources` should be a list of resources and not a single one. You should also only set this field if you want to fix the resources for this task. This makes sense if you already have a partial solution for a scenario and want to compute the position of all other tasks, which is of great help for local search heuristics, where you only want to swap some tasks around and leave the other tasks at their place.

Usually, you should not fill the `start` and `resources` field, but they are filled out during the computation. A corrected scenario looks like this:

````
import pyschedule
from pyschedule import ResourceReq
S = pyschedule.Scenario('delivery')

# Two trucks
Truck_A = S.Resource('A')
Truck_B = S.Resource('B')

# Customer
Customer = S.Resource('Customer')

# Two deliveries
a_deliver, a_unload, a_return = S.Task('a_deliver', 30), S.Task('a_unload', 15), S.Task('a_return', 30)
b_deliver, b_unload, b_return = S.Task('b_deliver', 30), S.Task('b_unload', 15), S.Task('b_return', 30)

# Only one resource (dock) for customer
S += a_unload % Customer
S += b_unload % Customer

# Task can be assigned to either truck
S.add_constraint(ResourceReq(tasks=[a_deliver, a_unload, a_return],
                             resources=[Truck_A, Truck_B]))

S.add_constraint(ResourceReq(tasks=[b_deliver, b_unload, b_return],
                             resources=[Truck_A, Truck_B]))
# Task sequences
S += a_deliver < a_unload, a_unload < a_return
S += b_deliver < b_unload, b_unload < b_return

# a_unload must happen before b_unload
S += a_unload <= b_unload

S.use_makespan_objective()
pyschedule.solvers.pulp.solve_discrete(S, horizon=100)
pyschedule.plotters.matplotlib.plot(S)
````

This should open a gantt-chart with the computed plan. P.S. S.is_same_resource_precs_lax has been removed due to redundancy. 

For your case, since `Customer` is anyway a required resource for `a_unload` and `b_unload`, adding `Customer` to `resources' should have no effect. However, since `a_unload` and `b_unload` also require other resources, this does not work so far, clearly a bug. In theory, it should also be possible to only fix `start` or `resources` (also with only a part to the resources), but that is also a little unreliable at the moment. The assumption at the moment is that either these field are complete, that is, both are filled and `resources` with all required resources (in your case also with some truck), or they should be empty (set to None).

Another option would be to return a separate solution object from the computation, but i think that writing the solution to the scenario is more accessible (very much a design decision). They method `clear_solution` clears a scenario from its solution.

hope this helps, please post any other problems.
