### ISSUE TITLE
Example in readme broken ? 

### ISSUE THREAD

**Issue by Zulko** [timnon/pyschedule#2]
When I run the example in the readme with the Github version of pyschedule.

```python
TypeError                                 Traceback (most recent call last)
<ipython-input-3-9c0022404aa0> in <module>()
      1 # Load pyschedule and create a scenario with ten steps planning horizon
      2 from pyschedule import Scenario, solvers, plotters
----> 3 S = Scenario('hello_pyschedule',horizon=10)
      4 
      5 # Create two resources

TypeError: __init__() got an unexpected keyword argument 'horizon'
```

And if I remove horizon it complains that solver.mip doesn't exist. Maybe update the example in the readme ?

**Comment by Zulko** [comment]
My bad, seems that my version of pyschedule hadnt updated correctly. Using the version on Github fixed the problem.

**Comment by timnon** [comment]
thanks, just also checked, having the horizon-parameter as a default is new, but it makes sense since open-end planning horizons are quite uncommon, there is usually an upper bound.

I would be very interested in having use cases to see what functionality is missing and if the running times of the formulations are practical. So feel free to post use cases as an issue, very appreciated!
