### ISSUE TITLE
optional breaks in timetable & prevent end-of-day overrun

### ISSUE THREAD

**Issue by zheffie** [timnon/pyschedule#46]
I have a horizon of 40, corresponding to 5 days of 8 hours.
There are tasks with length = 1, 2, 3 or 4 hours. 
Tasks can be randomly placed during daytime, but they cannot overrun the end of day, and they must remain 'whole'

How do I model this constraint?

**Comment by zheffie** [comment]
Nevermind. Think I found the solution already. I will add 4 additional slots corresponding to the end of day (horizon = 44), and will create 4 extra tasks constrained to these additional slots.

**Comment by timnon** [comment]
sounds like a good solution. If you have any real-world examples, please contribute to the examples section.

**Comment by timnon** [comment]
I would use blocking tasks for breaks with length 1. Think of a break as a task like anything else. You can make breaks optional by giving it a negative "schedule_cost" like `break = S.Task('break',schedule_cost=-1)`. Hence, scheduling a break will remove 1 from the final objective cost, and so the solver will try to schedule as many breaks as possible (all if possible).

To make sure that days end earlier, you can add some `time_cost` to tasks, like `T = S.Task('T',time_cost=1)`. This this add 1 to the final objective for each period task T is delayed, and hence it will try to schedule tasks as early as possible.

**Comment by zheffie** [comment]
Thanks for your reply. Much appreciated.

Does using blocking tasks imply that I have to break up my 4-hour tasks (T4) in 2 tasks of 2 hours (T4_1 and T4_2)? And add an additional constraint to make sure that they are consecutive, but take the break into account? eg T4_2 >= T4_1 +1

**Comment by timnon** [comment]
No, you shouldnt split up the tasks. As you write, you need to take the time of the breaks into account. The first solution is to add them already to the tasks in case they bridge a break, e.g. instead of setting ` `T4 = S.Task('T4',length=2)` set `T4 = S.Task('T4',length=3). The time scale might be distorted since your breaks are probably relatively short compared to your courses, but it will give you the logically correct result.

If you dont want to distort your time scales, you can also set breaks of length 0, like `break = S.Tash('break',length=0)`. In the standard plot, a break will then be plotted with length 0.5.

If your breaks are not much shorter than you courses, you could also adjust the time scale to then, e.g. if your breaks have length 15min, then set `T4 = S.Task('T4',length=9)` and break = S.Task('break',length=1)`. But dont do this if your breaks are really short like 5min in comparison to 2hour courses, this would create quite a lot of periods.

In all cases you need to fix the time of the break by setting `S += break >= <your break time>

**Comment by zheffie** [comment]
Thanks again for your answer. In the meantime I went ahead and split up my tasks which resulted into a working solution. 

But based on your response I will revisit and try the other approaches you proposed.

**Comment by timnon** [comment]
cool, if you have some running real-world example, please post sth or contribute directly to the examples folder. This is an interesting use-case

**Comment by adamgotterer** [comment]
@zheffie how did you end up solving the end of day overrun?

**Comment by zheffie** [comment]
I created a dedicated timeslot for the end of day, and a task constrained to that timeslot. This prevents other tasks from occupying the end of day slot

**Comment by adamgotterer** [comment]
@zheffie thanks, did you just set the period to constrain it or something else?

**Comment by zheffie** [comment]
eg. define task `T1` with `lenght=1` as the `end-of-day task`, and constraint it with a tight bound: `T1 >= 8` (assuming slot 8 to 9 is the `end-of-day slot`)
