### ISSUE TITLE
Specify resource start time

### ISSUE THREAD

**Issue by HBouch** [timnon/pyschedule#49]
Hello sir,
First, I want to thank you for this outstanding package.
How can I specify a start time for a resource ? the objective is to oblige all resources to start at time = 0.
Thank you in advance !

**Comment by timnon** [comment]
@HBouch there is no way to specify a start time so far, the canonical solution is to specify a task that blocks the resource until your start time, e.g. 

T = S.Task('blocker',length=your_wanted_start_time)
T += R
S += T >=0
The last constraint forces task T to start at time 0

It might make sense to allow the specification of start and end times of resources, because adding blocking tasks adds additional load on the solver. Keep this issue open, I will check whether this is possible without any conflicts.

Please contribute real-world examples to the examples section or post them here, always happy to receive some feedback

**Comment by HBouch** [comment]
Okay, thank you very much Sir.

**Comment by zheffie** [comment]
Suppose I make a resource available for slots `[0,1]` and `[2,3]`  (eg, `S.Resource('my_resource',periods=[[0,1],[2,3]])` and have a task of length 2. Will this setup prevent the task to be planned in slots `[1,2]`?

**Comment by KindlyFire** [comment]
Thank you very much for adding the `periods` attribute. I depend on it to build my classroom schedules.

Maybe close the issue ?
