### ISSUE TITLE
Enable two tasks to use the same resource but only if the tasks have something in common

### ISSUE THREAD

**Issue by kindlyfire** [timnon/pyschedule#58]
Hello,

First of all I'd like to say you made some amazing piece of software ! I really love it.

I'm using it to create schedules for my school. I was able to successfully create a schedule and everything, but I wonder about something I would really need.

Our school has grades (1, 2, 3, 4, 5, 6), separated into classes (1 Group a, 1Gb, 1Gc, 1Gd, 2Ga, 2Gb, ...). Each class is a resource, and each of the teachers is also a resource. Each exam is a task.

Tasks are like so: each task has a teacher resource, and a resource for every class that has that exam. Here is an example rendered schedule (the first four lines are what I am looking for):

![figure_1](https://user-images.githubusercontent.com/10267586/43994455-64e18802-9d9d-11e8-8537-6ae5ab14f26a.png)

I have one teacher, here named Derenne_C., that gives "5_sc_general" and "5_a_bio". The thing is, as all students in the grade 5 take exams in a common place, he can give the exams at the same time (in the eyes of the program, he would be at two places at the same time, so he cannot). Across grades though, this is not possible (he can give to exams for grade 5 at the same time, but he cannot give an exam for grade 4 and an exam for grade 5 at the same time).

Here's a [gist](https://gist.github.com/KindlyFire/c372c24e3ee5ff0e1cc58a99ad910546) of my code. I store teachers data, class data, etc. in a config.yml file in order for it not to look like [this](https://github.com/timnon/pyschedule/blob/master/example-notebooks/school-timetable-aisl.ipynb).

Is there a way of doing this ?

Thank you !

**Comment by KindlyFire** [comment]
> restrict the parallel processing to one type of task

I'd need parallel processing of groups of multiple types of tasks. Eg., he can do [Task1, Task2] at the same time and [Task3, Task4] at the same time, but not [Task1, Task3]

**Comment by timnon** [comment]
Yes, i think i understood the problem, like in the example above, having two green or red courses in parallel would be ok, but not a mix of red and green

**Comment by KindlyFire** [comment]
Is there any way I could help ? I saw you created the `add_capacities` branch and made a commit, is there any way of testing ?

**Comment by timnon** [comment]
The `add_capacities` branch is indeed the branch with the required features. It would be great if you could test this branch. It is now possible to do the following

```
from pyschedule import Scenario, solvers, plotters, alt

horizon = 20
S = Scenario('parallel_courses',horizon=horizon)

#size 2 means teacher can do two things in parallel
Teacher = S.Resource('T',size=2)

Courses_English = S.Tasks('CE',num=10,completion_time_cost=1,plot_color='red',english=1)
Courses_Math = S.Tasks('CM',num=10,completion_time_cost=1,plot_color='green',math=1)

Courses_English += Teacher
Courses_Math += Teacher

# NEW FEATURES: adding capacities and .max
S += Teacher['english'][0:horizon:1].max + Teacher['math'][0:horizon:1].max <= 1

if solvers.mip.solve(S,time_limit=600,msg=1):
    plotters.matplotlib.plot(S,show_task_labels=True)
else:
    print('no solution found')
```
To explain: `Teacher['english'][0:horizon:1].max` gives the sequence of capacity slices
```
Teacher['english'][0:1].max, Teacher['english'][1:2].max, ... , Teacher['english'][horizon-1:horizon].max
```
and e.g. `Teacher['english'][0:1].max` is the maximum `english`-param of any task in period 0 (this is the python slice notation of all periods t with 0 <= t < 1). Since all english course have `english=1`, this just measures if there is any english course scheduled on resource Teacher in period 0. Therefore, `Teacher['english'][0:1].max + Teacher['math'][0:1].max` is 2 if both an english and a math course are scheduled on resource Teacher in period 0, the case we want to avoid by using the constraint `<= 1`. The final result is hence correct, there are either two english courses or two math courses scheduled in each period:

![figure_1](https://user-images.githubusercontent.com/5597397/44300184-270a0e80-a303-11e8-94bb-ec6550b659f6.png)

**Comment by KindlyFire** [comment]
I think I got how to do it, though I have a question. The way I see this is that it is implemented as a black-list, "can't do that and that at the same time", although I'm looking to make it a whitelist: "cant do two things at the same time, except for these two specific courses". Is there a way I can achieve that ?

I know I could implement a white-list as a black-list (add a constraint for EVERY course except two of them), but that would add a lot of constraints, growing what I guess is exponentially, when the number of classes goes up.

**Comment by kindlyfire** [comment]
I haven't been able to get it implemented yet. I will do so in the next days.

**Comment by timnon** [comment]
adding capacities and max-capacities are now in the master branch
