### ISSUE TITLE
Running README example returns different result

### ISSUE THREAD

**Issue by kylecarbon** [timnon/pyschedule#72]
I'm on `pyschedule v0.2.31` and `python v3.5.2`. When I run the README example (from my terminal, I run `python3`, then copy+paste from the README), I get the following solution:
```
[(clean, Alice, 0, 3), (wash, Bob, 1, 3), (cook, Alice, 5, 6)]
```
![image](https://user-images.githubusercontent.com/24921149/49903224-5b0dc000-fe1b-11e8-930b-881498c08393.png)

This doesn't match what is listed on the homepage and I'm not sure where else to start. I'm sure I'm missing some other useful information, so let me know what else I can/should provide!

Also, sorry if this duplicates #2 but (i) I didn't want to comment on a closed issue and (ii) it's a different underlying issue.

**Comment by timnon** [comment]
Sorry for the late reply, the README was indeed not up-to-date, the completion time cost used to be automatically set to 1, but this was removed since this slighly decreases the performance in case it is not needed. But with the single line `S.use_flowtime_objective()` this can be set manually to ensure that all tasks are pushed to the "left".
