### ISSUE TITLE
Prevent exceeding a period

### ISSUE THREAD

**Issue by adamgotterer** [timnon/pyschedule#73]
Thank you for your work on pyschedule. It's looks like a terrific library. I'm playing around with it and have few questions:

1) I'm using a 24 hour horizon to represent a day of work and using periods to constrain a resources to a working schedule. I'm trying to block a task from being scheduled if it's going to exceed the working hours that resource has allocated even if it starts during their working hours. Here's the code I'm working with:

```python
from pyschedule import Scenario, solvers, plotters
S = Scenario('hello_pyschedule',horizon=24)

Alice = S.Resource('Alice', periods=range(9,18))
Bob = S.Resource('Bob', periods=range(9,18))

suite1 = S.Task('Suite1', length=6, completion_time_cost=1, periods=range(15,18))

suite2 = S.Task('Suite2', length=2, completion_time_cost=1, periods=range(12,18))
suite2_room2 = S.Task('Suite2_Room2', length=1, completion_time_cost=1)
S += suite2 < suite2_room2

suite3 = S.Task('Suite3', length=3, completion_time_cost=1)

suite1 += Alice | Bob
suite2 += Alice | Bob
suite3 += Alice | Bob
suite2_room2 += Alice | Bob

solvers.mip.solve(S,msg=1)
print(S.solution())
```

```
[(Suite3, Bob, 9, 12), (Suite2, Bob, 12, 14), (Suite2_Room2, Bob, 14, 15), (Suite1, Bob, 15, 21)]
```

As you can see Suite1 is scheduled to go to hour 21, but I'd like it to be blocked because it shouldn't exceed 18. I've gone through several issue tickets but couldn't quite figure this out. I tried playing with adding a length constraint to the resource with no luck. Any thoughts?

2) Whats the suggested way to specify an exact time for a task?

3) Is it possible to use this library to tell where a task could fit based on an exiting schedule. For example I'd like to be able to show my users some time options that would be available for them to schedule a task. So given an unscheduled task with constraints is it possible to see all the times or time ranges it could fit into?

Thanks!

**Comment by timnon** [comment]
1) The `periods` are the possible starting! periods of tasks, so if your task has length `6`, you could simply reduce the periods to `range(15,12)` in order to ensure that the task is not scheduled later than 18. Another way is to add the constraint `S += suite1 < 18`. Does this answer the question?

2) The easiest way to specify the exact time is to e.g. set `S += suite1 >= 16`. The `>=` means exactly larger than 16.

3) Not directly. One way to implement this is to compute a schedule, and then block the suggested slot with some artificial other task. Then reschedule and see if there is another option etc. Repeat until no more slot is found. There might be a lot of possible places where to schedule sth, so there needs to be some strategy which ones make sense to present. Some might also be overlapping.

**Comment by adamgotterer** [comment]
Thanks, that's very helpful!
