### ISSUE TITLE
cpoptimizer and ortools are raising errors

### ISSUE THREAD

**Issue by adamgotterer** [timnon/pyschedule#76]
I'm trying to test out some of the other optimizers to see if they will solve a larger horizon problem faster then pulp.

When I execute `cpoptimizer` I get:

```
Traceback (most recent call last):
  File "debug.py", line 56, in <module>
    solvers.cpoptimizer.solve(S)
  File "/usr/local/lib/python3.7/site-packages/pyschedule/solvers/cpoptimizer.py", line 264, in solve
    dat_filename, task_to_id, id_to_resource = _get_dat_filename(scenario,msg=msg)
  File "/usr/local/lib/python3.7/site-packages/pyschedule/solvers/cpoptimizer.py", line 155, in _get_dat_filename
    for C in S.capacity_up() :
AttributeError: 'Scenario' object has no attribute 'capacity_up'
```

and when I run ortools I get:

```

Traceback (most recent call last):
  File "debug.py", line 56, in <module>
    solvers.ortools.solve(S, msg=0)
  File "/usr/local/lib/python3.7/site-packages/pyschedule/solvers/ortools.py", line 122, in solve
    for C in S.capacity_low():
AttributeError: 'Scenario' object has no attribute 'capacity_low'
```

**Comment by timnon** [comment]
These solvers are quite outdated, please use only the standard one. The original plan was to integrate different backend, but this is quite hard since they are all good for different purposes. So I stopped at some point since the syncing became too much work. I also realized that the time-discrete mip-formulation in the standard solver is quite competitive with cp bases ones like ortools for problems where the task lengths are quite uniform and the time horizon is not too large. So this is the jack-of-all-trades.

**Comment by timnon** [comment]
But if you are interested in integrating a particular one, I would be happy to support the effort.

**Comment by adamgotterer** [comment]
Thanks for the clarification. Might be worth mentioning in the docs that these aren't maintained.
