### ISSUE TITLE
Distributing tasks and giving tasks different "value"

### ISSUE THREAD

**Issue by synapticarbors** [timnon/pyschedule#9]
I've been playing around with pyschedule and was wondering if it was possible to get the either or both of the following behaviors given the libraries current features:
- Distribute tasks more evenly between resources. Say I have 3 resources each with a capacity of 3, and then I schedule 3 tasks that all occur at the same time. Given the following code, I end up with one of the 3 resources assigned with all 3 tasks, and the other two get no work. Is there a way to make it so that each resource is assigned 1 of the tasks instead?

```
from pyschedule import Scenario, solvers, plotters
import pyschedule

def test_setup():
    task_dt = 2
    task_len = 2*task_dt
    task_time = 10

    S = Scenario('test', horizon=20)
    resources = {name: S.Resource(name, size=3) for name in ['A', 'B', 'C']}
    tasks = {}
    for k in xrange(3):
        tasks[str(k)] = S.Task('task_{}'.format(k), task_len)
        T = tasks[str(k)]
        S += T >= task_time - task_dt
        S += T < task_time + task_dt

    for k in tasks:
        tasks[k] += pyschedule.alt(S.resources())
    return S

S = test_setup()
# Solve and plot scenario
if solvers.mip.solve(S, kind='CBC', msg=1, random_seed=6):
    %matplotlib inline
    plotters.matplotlib.plot(S, fig_size=(12,5))
else:
    print('no solution found')
```
- Given tasks that are scheduled at a fixed time (as in the above example), and there are not enough resources available at certain times to process all of the tasks that need to be completed, I'd like to assign each task a value, make each optional and them schedule them such that the sum of the values of the tasks that are assigned is maximized (or conversely the total value of the skipped tasks at a certain time is minimized). Is there a way to do this?

Thanks in advance for any insight anyone can provide.

**Comment by timnon** [comment]
Hi, 
sorry for the late answer, not sure if this is still work in progress.

First, since all your resources have size 3, they can run three tasks in parallel, so its valid that all tasks are assigned to one resource. Clearly, that is not a good solution. However, to equally balance tasks, you could write a small heuristic that iteratively decreases the resource size until no solution is found any more and then moves one step back. The current framework does not allow more involved objective functions at the moment, but I think that doing load balancing using some heuristic is ok.

Second, you would like to have some price-collecting setting. That would be a nice feature, but is currently not supported, I thought about this at some point, it is definitely sth that could be easily done if there is need. There is a little work-around by assigning different weights to the tasks in a flow-time objective, and then leave enough buffer time in the end to store all tasks which could not be finished within the "regular" time, like in https://github.com/timnon/pyschedule-notebooks/blob/master/crew-scheduling.ipynb

Did this help? Please post also complete problems you would like to solve:)

**Comment by sandragreiss** [comment]
Hi @timnon - is there a direct way to contact you? I've been playing with pyschedule all weekend and want to figure it out in the case of hotel room bookings where the rooms are resources with different sizes. I know we can add a size for resources but that will mean that they can schedule multiple tasks in parallel, leading to multiple bookings of the same room in parallel.

**Comment by timnon** [comment]
Hi,
thanks for the interest, what exactly do you want to express with the room
size? Maybe you want to express different room sizes as different resource
types, and then e.g. ensure that booking tasks with one person can be
assigned to room resources of type one or larger, etc. I am happy to
receive some feedback on the functionality and use cases, my number for
whatsapp is 0041764134260.
Best, Tim

**Comment by joe63** [comment]
duty roster:

morning-charge: 05:00 - 13:30
afternoon-charge: 13:30 - 22:00

7 days a week

3 colleagues as permanent staff and 1 colleague for holiday replacement

one free weekend per month for each colleague

36 continous hours free per week for each colleaque

when today afternoon-charge next day no morning-charge for the same colleague

only one charge a day from the same colleague 

specify days when a colleaque cannot make his charge

for example:

permanent staff J(an), M(arie), K(arl)
holiday replacem. Ka(ti)

V	N
-----	
J	M
M	K
M	K
M	J
M	J
M	K
J	K
J	K
J	M
J	M
K	M
K	M
Ka	J
Ka	J
K	Ka
J	Ka
J	K
J	K
J	K
M	K
M	K
J	M
J	M
J	M
J	K
M	K
M	K
M	J
K	M
K	J
K	J

is this manageable by pyschedule?

**Comment by djking7** [comment]
@timnon is their anyway to limit number of tasks in a resource? not length
